services:
  postgres:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: obook
    networks:
      obook-network:

  # backend: 
  #   build: 
  #     context: ./obook-be
  #     dockerfile: Dockerfile.local
  #     ports :
  #       - 3001:3001
  #     environment:
  #       DATABASE_URL: postgres://postgres@postgres/obook
  #       PORT: 3001
  #       SALT_ROUND: 12
  #       JWT_SECRET_KEY: minhbao
  #       CLOUDINARY_API_KEY: 549695228267364
  #       CLOUDINARY_API_SECRET: Q8ksXeJe_kNaVpAEeJLkjYkZob
  #     network: 
  #       obook-network:

  frontend:
    build: 
      context: ./obook-fe
      dockerfile: Dockerfile
    container_name: obook-fe
    ports :
      - 3000:3000
    volumes:
      - .:/usr/src/app/node_modules
      - /usr/src/app/node_modules
    environment:
      NEXT_PUBLIC_DOMAIN_SERVER: http://localhost:3001
    networks: 
      obook-network:

networks:
  obook-network:
    external: 
      name: obook-network
